FROM python:3.11-slim

# Instala dependências básicas e o cliente Docker
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    && curl -fsSL https://get.docker.com | sh \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Configura o diretório de trabalho
WORKDIR /app

# Copia os requisitos e instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY gerenciador.py .

CMD ["python", "-u", "gerenciador.py"]