version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    network_mode: "host"
    restart: always

  atuador:
    build:
      context: .
      dockerfile: Dockerfile.atuador
    network_mode: "host"
    depends_on:
      - backend

  sensor:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    network_mode: "host"
    depends_on:
      - backend